🐛 Disable out-of-bounds glyph placement
DDMAL/Neon pull request #911
Opened 2022-07-04 20:02 UTC by jinh0

Fixes #700 , at least for single glyphs / staves.

Now a notification will show up if you have placed a glyph out of bounds.

## Demo
https://user-images.githubusercontent.com/40512164/177211574-3e2e46cf-d6f5-484f-8d13-aa01cc2a8b2e.mov

2022-07-11 13:26 UTC, jinh0 commented on src/utils/SelectTools.ts
> +  return { id: staff.id, ulx, uly, lrx, lry, rotate, };
Shorten return with destructuring

2022-07-11 13:28 UTC, jinh0 commented on src/utils/DragHandler.ts
> +  resetTo (reset: (selection: d3.Selection<d3.BaseType, unknown, HTMLElement, unknown>, args: unknown[]) => void): void {
I had 3 warnings from ESlint every time I opened this file, so I finally just changed it to 'unknown'

2022-07-11 13:30 UTC, jinh0 commented on src/utils/Coordinates.ts
> +  const bgimg = document.querySelector<SVGImageElement>('#bgimg');
bgImg

2022-07-11 13:30 UTC, jinh0 commented on src/utils/Coordinates.ts
> +export function isInside (bbox: BBox, ul: Point, lr: Point): boolean {
specify point for ul and lr

2022-07-11 13:31 UTC, jinh0 commented on src/utils/DragHandler.ts
> +  isSelOutOfBounds (selection: SVGGraphicsElement[]): boolean {
rename to isDragOutOfBounds

2022-07-11 13:33 UTC, jinh0 commented on src/utils/Coordinates.ts
> +export function isInside (bbox: BBox, ul: Point, lr: Point): boolean {
dragUl and dragLr, and call the function isInsideDrag

2022-07-11 13:46 UTC, jinh0 commented on src/utils/Select.ts
> +function isWithinRect(d: SVGGraphicsElement, ul: Point, lr: Point): boolean {
isElementInRect

2022-07-12 03:48 UTC, yinanazhou requested changes
Weird behaviour needs to be solved before merging:
https://user-images.githubusercontent.com/74484576/178404594-b5b1a3bf-f679-4640-9325-c5c002e77a9b.mov

2022-07-13 03:50 UTC, yinanazhou requested changes
Noticed another issue about dragging: the bbox is dragged along with the syllable.
This only happens in this repo, should be fixed in this PR.

https://user-images.githubusercontent.com/74484576/178646715-a5918e05-e31f-4cb9-854d-fb705c8b44f0.mov

2022-07-13 03:52 UTC, yinanazhou commented
> Weird behaviour needs to be solved before merging: https://user-images.githubusercontent.com/74484576/178404594-b5b1a3bf-f679-4640-9325-c5c002e77a9b.mov

After discussion, this is now in issue #919, will be fixed in a separate PR.

2022-07-14 03:21 UTC, yinanazhou approved these changes

2022-07-14 03:22 UTC, merged